# List of sample IDs --> .BAM
# Maybe change the variable i dkno
samples:
  - sample1
  - sample2
  # etc 

# Select what assembler you want to use: flye or hifiasm
assembler: flye

# Estimated genome size (for flye and QUAST), QUAST only supports the raw number instead of the "500m"
genome_size: "500000000"

threads:
  samtools: 16
  porechop: 16
  flye: 32
  hifiasm: 32
  medaka: 8 # still idkno if im gonna use it
  purge_haplotigs: 16
  kraken2: 16
  quast: 8
  busco: 16
  multiqc: 8
  nanostat: 8 # i found an alternative: cramino https://github.com/wdecoster/cramino

flye:
  read_type: "--nano-hq"    # --nano-raw # --nano-hq # --pacbio-raw # --pacbio-hifi
  extra_args: ""

hifiasm:
  extra_args: ""

medaka:
  model: "r1041_e82_400bps_hac_g632"   # i dkno if we need to use it
  extra_args: ""

purge_dups:
  extra_args: ""

kraken2:
  db: "data/kraken2_db" # path to Kraken2 db
  confidence: "0.1" # 0.1 for low conf, 0.2-0.5 for better results
  extra_args: ""

quast:
  extra_args: ""

busco:
  lineage: "fungi_odb10" # replace with your desired target lineage
  mode: "genome"
  extra_args: ""